### PR TITLE
Open existing tab if unique url is triggered

### PR DESCRIPTION
**Pull request by mauricecruz**
Awesome plugin! One thing I found troublesome was that when I entered in a url that was considered unique, it would close the tab. I would then have to find the unique tab amongst my current tabs.

This PR opens the tab in question.

### CODE REVIEW

**Comment by sylouuu** [comment]
Hi @mauricecruz,

Thanks for contributing!

The auto-focus on unique tab was previously supported until someone reported an unexcepted behavior described in #23. I decided to remove the auto-focus.

Can you give me your feedback?

Bests

**Comment by mauricecruz** [comment]
Ahh - good to know the background. Hmm, a few things come to mind.

Is there a way to distinct between a tab refresh and a new tab opening? Wondering why a new tab id is being generated if the same tab is being refreshed.

If that's not possible, perhaps a GUI option to ask the user if they want to focus on the existing tab in the case of uniques. That will make both scenarios supported.

**Comment by sylouuu** [comment]
> Is there a way to distinct between a tab refresh and a new tab opening? Wondering why a new tab id is being generated if the same tab is being refreshed.

Not really possible or easy to distinct. There is always a tab id.

> If that's not possible, perhaps a GUI option to ask the user if they want to focus on the existing tab in the case of uniques. That will make both scenarios supported.

It seems overkill to my opinion for a non-mandatory feature, not much used (I think).

**Comment by sylouuu** [comment]
Is that OK for you if I close this?

Bests

**Pull request closed without merging**
