### PR TITLE
Allow Custom Url Data in the Title

### PR DESCRIPTION
**Pull request by jessehouchins**
Added a `url_parms` option to match custom data from the url using regexp. This variable data can then be used as part of the title, just like `{title}`.

```
// EXAMPLE:

{
  "github.com" : {
    "title" : "[{repo}] {title}",
    "url_params" : {
      "repo" : "github\\.com\/[A-Za-z0-9\\-\\_]+\/([A-Za-z0-9\\-\\_]+)"
    }
  }
}

// CONVERTS: "github.com/user/repo-name/pulls/123" --> "[repo-name] Pull Request Title"
```

Tests included.

### CODE REVIEW

**Comment by sylouuu** [comment]
Hi @jessehouchins,

Thank's for your contribution. Your feature as exposed seems really GitHub specific and not easy to adapt for other needs, don't you think?

Bests

**Comment by jessehouchins** [comment]
What do you mean? you can pull anything from the url that you like... it's all configuration.

**Comment by sylouuu** [comment]
Why are you doing `match[1];`?

What if you want to retrieve the username?

**Comment by jessehouchins** [comment]
I suppose I could allow any number of matches and just use $1, $2, etc in the title as replacement tokens. That might make more sense

**Comment by sylouuu** [comment]
Sounds better. Can you update your code with this behavior and give multiple examples.

Of course, please make additional tests.

Bests

**Comment by jessehouchins** [comment]
yep

**Comment by jessehouchins** [comment]
Updated and added examples to the readme.

**Comment by jessehouchins** [comment]
It seems there still may a bug in here, or my dev build is messed up.... let you know when it's resolved.

**Comment by jessehouchins** [comment]
seems ok now.

**Comment by sylouuu** [comment]
Hey @jessehouchins,

Although I don't think this feature will be very useful (seems very specific), can you just resubmit your PR into `release/0.6.0` branch?

Bests

**Pull request closed without merging**
