### PR TITLE
Url vars

### PR DESCRIPTION
**Pull request by jessehouchins**

### CODE REVIEW

**Comment by jessehouchins** [comment]
do you want to handle conflicts?

**Comment by sylouuu** [comment]
It's ok, thx @jessehouchins.

Stay tuned for `0.6.0` in few weeks.

**Comment by sylouuu** [comment]
Hi @jessehouchins,

Consider this settings:

```json
    "title": "{title} | $2 by $1",
    "url_matcher": "github\\.com/([A-Za-z0-9\\-\\_]+)/([A-Za-z0-9\\-\\_]+)"
}
```

It's ok if you are browsing a repo but go to https://github.com/issues or any non-repo based URI. You will see in the title `Issues | $2 by $1`. Not really pretty.

What do you think about this?

Bests

**Comment by sylouuu** [comment]
Supported in [0.6.0](https://github.com/sylouuu/chrome-tab-modifier/releases/tag/0.6.0).

**Pull request merged**
