### PR TITLE
updated title text selection with support for form elements

### PR DESCRIPTION
**Pull request by vaff**
I don't know if this is how you want it. It is really my first time trying to formulate a pull-request.

But I had a issue with the querySelector that gets text for the title. In some cases i wanted to use both a input and a select. So I made a minor modification to handle this case.

### CODE REVIEW

**Comment by sylouuu** [comment]
Hi @vaff,

Pretty good! Thanks!

**Comment by vaff** [comment]
My editor does all the line end stripping automatically. Hope it's not an issue.

**Comment by sylouuu** [comment]
No worry it's OK!

**Comment by sylouuu** [comment]
Available in 0.18.1!

**Pull request merged**
